server.port=8080

spring.application.name=api-gateway

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.server.webflux.routes[1].id=job-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://JOB-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/jobs/**

spring.cloud.gateway.server.webflux.routes[2].id=profile-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://PROFILE-SERVICE
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/profiles/**

spring.cloud.gateway.server.webflux.routes[3].id=application-service
spring.cloud.gateway.server.webflux.routes[3].uri=lb://APPLICATION-SERVICE
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/applications/**

spring.cloud.gateway.server.webflux.routes[4].id=notification-service
spring.cloud.gateway.server.webflux.routes[4].uri=lb://NOTIFICATION-SERVICE
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/api/notifications/**

spring.cloud.gateway.server.webflux.routes[5].id=interview-service
spring.cloud.gateway.server.webflux.routes[5].uri=lb://INTERVIEW-SERVICE
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/api/interviews/**